version: "3.8"

services:
  debugger:
    container_name: debugger
    hostname: debugger
    image: shoaibi/debugger:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
      target: debug
    volumes:
    - ./src:/go/src/debugger
    ports:
    - 2345:2345
    security_opt:
      # Required for debugger to fork process
      - "seccomp:unconfined"
    cap_add:
      - "SYS_PTRACE"
